services:
  backend_api:
    build:
      context: ./backend
    container_name: backend_api_container
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    env_file:
      - ./backend/.env
    networks:
      - app_network

  frontend_ui:
    build:
      context: ./frontend
    container_name: frontend_ui_container
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    networks:
      - app_network

  postgres_db:
    image: postgres:latest
    container_name: postgres_db_container
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      # Uncomment the following line for persistent data storage
      # - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_SERVER}
    networks:
      - app_network

  database_admin:
    image: adminer:latest
    container_name: database_admin_container
    ports:
      - "8080:8080"
    networks:
      - app_network

  nginx_proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_container
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - postgres_db
      - backend_api
      - frontend_ui
      - database_admin
    networks:
      - app_network

volumes:
  data:
  letsencrypt:
  postgres_data:

networks:
  app_network:
    external: true
