services:
  backend:
    build:
      context: ./backend
    container_name: BE-Container
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: FE-Container
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - "8080:8080"
    networks:
      - app-network

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager-container
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
      - backend
      - frontend
      - adminer
    networks:
      - app-network

volumes:
  data:
  letsencrypt:


networks:
  app-network:
    external: true
